### ISSUE TITLE
CSS Optimization

### ISSUE THREAD

**Issue by mic-andrew** [vi-ta-lis/Spotify-Premium#1]
1. Instead of this [this](https://github.com/vi-ta-lis/Spotify-Premium/blob/d59156424112d2fb341d24f328eeea87a4aedeb1/body.css#L98-L120)

you can do this
```
@media (max-width: 1100px) {
   .line1, .line5, .line4 {
      display: flex;
      flex-direction: column;
      gap: 20px; 
   }
}
````

2. Instead of repeating most of the elements [here](https://github.com/vi-ta-lis/Spotify-Premium/blob/d59156424112d2fb341d24f328eeea87a4aedeb1/body.css#L41-L74), you can have one base class that has similar properties defined in it. 

```
.btn {
    font-weight: bold;
    height: 40px;
    border-radius: 18px;
    cursor: pointer;
    color: white;
    border-width: 0;
}

.btn:hover {
    transform: scale(1.1);
}

.btn1 {
    margin-left: 300px;
    width: 170px;
    background-color: rgb(110, 23, 23);
}

.btn2 {
    width: 150px;
    border: 1px solid white; /* Vitalis take note of the shorthand property to set border-width, border-style, and border-color */
    background-color: black;
    margin-left: 8px;
}
```

The Html

```
<button class="btn btn1">Get Premium Individual</button>
<button class="btn btn2">View Premium plans</button>


```

**Comment by vi-ta-lis** [comment]
@Mykmicheals I have effected the change in the @mediaquery, but the second one, that .btn, some properties removed, so I had to add them myself. 

This did not work:   
.btn:hover {
    transform: scale(1.1);
}


 height: 40px;    cursor: pointer;    border-radius: 18px;   didn't work too.
